import {
  ElAutoResizer,
  ElButton,
  ElButtonGroup,
  ElCheckbox,
  ElCheckboxGroup,
  ElDialog,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElMessage,
  ElMessageBox,
  ElNotification,
  ElOption,
  ElOptionGroup,
  ElPagination,
  ElPopover,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElScrollbar,
  ElSelect,
  ElSelectV2,
  ElSkeleton,
  ElSlider,
  ElSwitch,
  ElTag,
  ElTable,
  ElTableColumn,
  ElTimeSelect,
  provideGlobalConfig,
} from "element-plus";
import zhCn from "element-plus/es/locale/lang/zh-cn";

const components = [
  ElAutoResizer,
  ElButton,
  ElButtonGroup,
  ElCheckbox,
  ElCheckboxGroup,
  ElDialog,
  ElDropdown,
  ElDropdownItem,
  ElDropdownMenu,
  ElEmpty,
  ElForm,
  ElFormItem,
  ElIcon,
  ElInput,
  ElInputNumber,
  ElOption,
  ElOptionGroup,
  ElPagination,
  ElPopover,
  ElProgress,
  ElRadio,
  ElRadioButton,
  ElRadioGroup,
  ElScrollbar,
  ElSelect,
  ElSelectV2,
  ElSkeleton,
  ElSlider,
  ElSwitch,
  ElTag,
  ElTable,
  ElTableColumn,
  ElTimeSelect,
];

export function installElementPlus(app) {
  provideGlobalConfig({ locale: zhCn }, app, true);
  components.forEach((component) => app.use(component));
}

export { ElMessage, ElMessageBox, ElNotification };
